import {DAYS,dateKey,fromKey,shift,due,completionKey,streak,normalizePlan,mergeEntries,tasksOn,toggleCompletion,orderTasks} from './engine.js?v=3';
import {createSounds} from './sounds.js?v=3';
import {reorderTaskCards} from './task-motion.js?v=3';
const sounds=createSounds();sounds.preload();

const KEY='my-daily-brief-v1';
const app=document.querySelector('#app'),dialog=document.querySelector('#modal'),modalBody=document.querySelector('#modal-body');
let today=dateKey(),selected=today,view='today',storageOK=true,importDraft=null,timerPreset=25,toastTimeout;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,cls='')=>`<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const id=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const longDate=d=>fromKey(d).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});
const shortDate=d=>fromKey(d).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const repeatLabel=h=>h.repeat==='daily'?'Every day':h.repeat==='weekdays'?'Monday – Friday':h.repeat.map(d=>d.slice(0,1).toUpperCase()+d.slice(1)).join(', ');
function starter(){return {version:1,tasks:[{id:'starter-study',title:'A little deep work',date:today,time:'09:00',minutes:45,category:'study',notes:'Choose one chapter. Read it slowly, then explain the main idea in your own words.'},{id:'starter-practice',title:'Put your knowledge to work',date:today,time:'11:00',minutes:25,category:'practice',notes:'Try a few practice questions without looking at the answers. Add your actual study plan through Import JSON.'},{id:'starter-review',title:'Review your tricky bits',date:today,time:'18:00',minutes:15,category:'review',notes:'Revisit the questions that challenged you. One lesson learned is a win.'}],habits:[{id:'starter-walk',title:'Morning walk',startDate:today,repeat:'daily',icon:'walk'},{id:'starter-chess',title:'A little chess',startDate:today,repeat:'daily',icon:'chess'},{id:'starter-studies',title:'Show up to study',startDate:today,repeat:'weekdays',icon:'book'}],completions:{},settings:{sound:true,soundDefaultVersion:3,motion:true,starter:true},focus:null};}
let state;
try{const saved=localStorage.getItem(KEY);if(saved){const raw=JSON.parse(saved);const clean=normalizePlan(raw);state={...clean,completions:clean.completions||{},settings:{sound:true,motion:true,starter:false,...raw.settings},focus:raw.focus&&Number.isFinite(raw.focus.remaining)&&raw.focus.remaining>=0&&raw.focus.remaining<=86400&&(!raw.focus.endAt||Number.isFinite(raw.focus.endAt))?raw.focus:null};}else state=starter();}catch{state=starter();storageOK=false;}
// Switch existing installations to the requested sound-on default once; preserve later mutes.
if(state.settings.soundDefaultVersion!==3){state.settings.sound=true;state.settings.soundDefaultVersion=3;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;toast('Storage is unavailable. Export a backup to keep your plan.');}}
if(storageOK)save();
function applyMotion(){document.documentElement.classList.toggle('reduce-motion',!state.settings.motion);}
applyMotion();
const isDone=(type,item,date)=>!!state.completions[completionKey(type,item.id,date)];
const xp=()=>Object.keys(state.completions).reduce((n,k)=>n+(k.startsWith('t|')?10:5),0);
function dailyStreak(){let n=0,d=today;const won=new Set(Object.keys(state.completions).map(k=>k.split('|')[2]));if(!won.has(d))d=shift(d,-1);while(won.has(d)&&n<3660){n++;d=shift(d,-1);}return n;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('visible'),3500);}
function playFeedback(name='complete'){
  if(!state.settings.sound)return Promise.resolve(false);
  return sounds.play(name).then(()=>true).catch(()=>false);
}

function syncSettings(){
  document.querySelectorAll('[data-action="sound"]').forEach(button=>{button.setAttribute('aria-checked',String(state.settings.sound));button.querySelector('.switch')?.classList.toggle('on',state.settings.sound);});
  const label=document.querySelector('[data-sound-label]');if(label)label.textContent=state.settings.sound?'Completion sound is on':'Completion sound is off';
  document.querySelectorAll('[data-action="motion"]').forEach(button=>{button.setAttribute('aria-checked',String(state.settings.motion));button.querySelector('.switch')?.classList.toggle('on',state.settings.motion);});
}
async function toggleSound(){
  state.settings.sound=!state.settings.sound;save();syncSettings();
  if(state.settings.sound){const played=await playFeedback('complete');toast(played?'Sound on. That’s your completion chime!':'Sound on for your next completion.');}
  else{sounds.stop();toast('Sound off. Quiet wins count too.');}
}
function celebrate(origin,reward){
  void playFeedback();
  if(!state.settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const el=document.querySelector('#confetti'),rect=origin?.getBoundingClientRect();
  const x=rect?rect.left+rect.width/2:innerWidth/2,y=rect?rect.top+rect.height/2:innerHeight*.4;
  const burst=document.createElement('div');burst.className='celebration-burst';burst.style.left=x+'px';burst.style.top=y+'px';
  burst.innerHTML=Array.from({length:14},(_,i)=>`<span class="confetti-piece" style="--x:${(Math.random()-.5)*150}px;--y:${Math.random()*125-90}px;--r:${Math.random()*500-250}deg;background:${['#b9a2f4','#c4e970','#f9aeca','#ffd189'][i%4]};animation-delay:${Math.random()*50}ms"></span>`).join('')+(reward?`<span class="reward-bubble">+${reward} XP</span>`:'');
  el.append(burst);setTimeout(()=>burst.remove(),1100);
  const mascot=document.querySelector('.buddy-body');if(mascot){mascot.classList.remove('celebrating');requestAnimationFrame(()=>{mascot.classList.add('celebrating');setTimeout(()=>mascot.classList.remove('celebrating'),650);});}
}

function buddy(){return `<div class="buddy" aria-hidden="true"><svg viewBox="0 0 160 150"><ellipse class="buddy-shadow" cx="80" cy="139" rx="44" ry="7" fill="#3c2256" opacity=".14"/><g class="buddy-body"><path d="M64 108q-8 20-8 23" fill="none" stroke="#34313b" stroke-width="5" stroke-linecap="round"/><path d="M95 108q9 19 10 22" fill="none" stroke="#34313b" stroke-width="5" stroke-linecap="round"/><path d="M58 126q-18 0-19 8 0 5 24 3l2-9" fill="#34313b"/><path d="M102 125q20 2 23 10-1 5-25 2l-2-9" fill="#34313b"/><path d="M43 80q-16 5-20-8" fill="none" stroke="#34313b" stroke-width="4" stroke-linecap="round"/><g class="buddy-arm"><path d="M120 82q15 3 19-13" fill="none" stroke="#34313b" stroke-width="4" stroke-linecap="round"/><path d="M138 67v-7m2 8 5-4m-8 3-4-4" fill="none" stroke="#34313b" stroke-width="3" stroke-linecap="round"/></g><path d="M76 28q4-7 8 0l12 22 25 4q9 1 3 9l-17 20 2 26q1 9-7 5L80 102l-25 12q-8 4-7-5l3-26-18-19q-6-7 3-10l27-4Z" fill="#edfb9e" stroke="#3d383c" stroke-width="2.1" stroke-linejoin="round"/><path d="m65 51 12-20" stroke="#f9ffdb" stroke-width="4" stroke-linecap="round"/><g class="buddy-eye"><ellipse cx="68" cy="72" rx="3.3" ry="5.2" fill="#34313b"/><ellipse cx="91" cy="72" rx="3.3" ry="5.2" fill="#34313b"/></g><ellipse cx="58" cy="81" rx="6" ry="3.7" fill="#f2b7ad" opacity=".85"/><ellipse cx="103" cy="81" rx="6" ry="3.7" fill="#f2b7ad" opacity=".85"/><path d="M73 84q7 9 14 0" stroke="#34313b" stroke-width="2.6" fill="none" stroke-linecap="round"/></g></svg></div>`;}
function checkButton(type,item,date,disabled=false){const done=isDone(type,item,date);return `<button class="check-button ${done?'done':''}" data-action="complete" data-type="${type}" data-id="${escape(item.id)}" data-date="${date}" aria-label="${done?'Undo':'Complete'} ${escape(item.title)}" aria-pressed="${done}" ${disabled?'disabled':''}><span class="check-circle">${icon('check')}</span></button>`;}
function taskCard(t){const done=isDone('t',t,t.date);return `<article data-task-id="${escape(t.id)}" class="task ${done?'done':''}"><div class="task-icon ${t.category}">${icon(t.category==='practice'?'spark':t.category==='review'?'clock':t.category==='personal'?'heart':'book')}</div><div class="task-info"><button class="task-detail-button" data-action="task-detail" data-id="${escape(t.id)}"><span class="task-title">${escape(t.title)}</span><span class="task-meta">${t.time?`<b>${escape(t.time)}</b><span class="separator">·</span>`:''}${icon('clock')}${t.minutes} min<span class="separator">·</span><span>${t.category==='study'?'Deep work':t.category==='practice'?'Practice':t.category==='review'?'Reflect':'Personal'}</span>${t.date<today&&!done?`<span class="overdue">· Due ${shortDate(t.date)}</span>`:''}</span></button></div>${checkButton('t',t,t.date,t.date>today)}</article>`;}
function weekStrip(){let first=shift(selected,-((fromKey(selected).getDay()+6)%7));return `<div class="week-strip" aria-label="Choose a day">${Array.from({length:7},(_,i)=>{const d=shift(first,i);return `<button class="day ${d===selected?'selected':''} ${d===today?'today':''}" data-action="date" data-date="${d}" aria-label="${longDate(d)}" aria-pressed="${d===selected}"><span>${fromKey(d).toLocaleDateString(undefined,{weekday:'short'}).slice(0,1)}</span><strong>${fromKey(d).getDate()}</strong>${state.tasks.some(t=>t.date===d)?'<span class="day-dot"></span>':''}</button>`;}).join('')}</div>`;}
function focusBanner(){if(!state.focus)return '';return `<button class="active-focus" data-action="focus">${icon('clock')}<span>${state.focus.endAt?'Focus time is ticking':'Your focus session is paused'}</span><b data-timer-label>${timerText()}</b></button>`;}
function syncFocusBanner(){const old=app.querySelector('.active-focus');if(old){const draft=document.createElement('div');draft.innerHTML=focusBanner();old.replaceWith(draft.firstElementChild);}else if(state.focus&&view==='today'){app.querySelector('.daily-progress')?.insertAdjacentHTML('beforebegin',focusBanner());}}

function todayView(){
  const tasks=tasksOn(state.tasks,state.completions,selected,today),habits=state.habits.filter(h=>due(h,selected));
  const done=tasks.filter(t=>isDone('t',t,t.date)).length+habits.filter(h=>isDone('h',h,selected)).length,total=tasks.length+habits.length,percent=total?Math.round(done/total*100):0;
  const dayXP=tasks.filter(t=>isDone('t',t,t.date)).length*10+habits.filter(h=>isDone('h',h,selected)).length*5;
  return `<div class="page-heading"><div><p class="eyebrow">${escape(longDate(selected))}</p><h1>${selected===today?'Make today<br>count.':'Your day,<br>your pace.'}</h1></div><div class="streak-pill" title="Consecutive days with at least one completed task or habit">${icon('flame')}${dailyStreak()} day${dailyStreak()===1?'':'s'}</div></div>
  <section class="hero"><div class="hero-copy"><p class="eyebrow">${done===total&&total?'LOOK AT YOU GO':'A FRESH LITTLE START'}</p><h2>${done===total&&total?'You showed up.<br>That’s a win.':'Small steps.<br>Big possibilities.'}</h2><p>${done===total&&total?'Take a breath. You earned it.':'A little focus, a little fun.<br>You’ve got this.'}</p></div>${buddy()}<span class="hero-star one">✦</span><span class="hero-star two">✧</span></section>
  ${weekStrip()}${focusBanner()}<div class="daily-progress"><div class="progress-ring" style="--progress:${percent}%" data-percent="${percent}%" role="img" aria-label="${percent} percent complete"></div><div class="progress-text"><strong>${done===total&&total?'A beautifully finished day':done?'Little wins are adding up':'Let’s get your first little win'}</strong><span>${done} of ${total} things completed</span></div><span class="xp-label">${icon('spark')}+${dayXP} XP</span></div>
  <div class="section-head"><h2>Your daily quests<span>${tasks.length}</span></h2><button class="text-button" data-action="add-task">${icon('plus')}Add task</button></div>
  <div class="task-list">${tasks.map(taskCard).join('')||empty('A little room to breathe','No tasks planned for this date. Add your study plan whenever you’re ready.','add-task','Add a task')}</div>
  <div class="section-head"><h2>The little rituals</h2><button class="text-button" data-action="navigate" data-view="habits">All habits${icon('arrow')}</button></div>
  <div class="habit-grid">${habits.map((h,i)=>`<article data-habit-id="${escape(h.id)}" class="habit-card ${['','pink','lilac','blue'][i%4]} ${isDone('h',h,selected)?'done':''}"><div class="habit-top"><div class="habit-symbol">${icon(h.icon)}</div>${checkButton('h',h,selected,selected>today)}</div><button class="habit-title" data-action="edit-habit" data-id="${escape(h.id)}">${escape(h.title)}</button><small>${icon('flame')}<span data-habit-streak="${escape(h.id)}">${streak(h,state.completions,today)}</span> day streak</small></article>`).join('')}</div>
  ${!habits.length?empty('Build a tiny ritual','A recurring habit is one less thing to plan.','add-habit','Add a habit'):''}
`;
}
function empty(title,text,action,label){return `<div class="empty-state">${icon('spark')}<h3>${title}</h3><p>${text}</p><button data-action="${action}">${label} →</button></div>`;}
function planView(){const tasks=state.tasks.filter(t=>t.date>=selected).sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'99').localeCompare(b.time||'99'));const groups=new Map();tasks.forEach(t=>{if(!groups.has(t.date))groups.set(t.date,[]);groups.get(t.date).push(t);});return `<div class="page-heading"><div><p class="eyebrow">A LITTLE DIRECTION</p><h1>Good days<br>start here.</h1></div>${icon('calendar')}</div><p class="subtitle">Your study schedule, one doable step at a time.</p><div class="toolbar"><button class="primary" data-action="import">${icon('upload')}Import JSON</button><button class="secondary" data-action="add-task">${icon('plus')}Add task</button></div><div class="date-control"><span>Show from</span><input type="date" aria-label="Show tasks from date" data-date-picker value="${selected}"></div>${tasks.length?`<p class="eyebrow">${tasks.length} PLANNED TASK${tasks.length===1?'':'S'}</p>`:''}${[...groups].map(([date,tasks])=>`<section class="plan-group"><h2 class="plan-group-title">${date===today?'Today · ':''}${escape(longDate(date))}</h2><div class="task-list">${orderTasks(tasks,state.completions).map(taskCard).join('')}</div></section>`).join('')||empty('Your next chapter awaits','Import a ChatGPT plan or add a study session to get started.','import','Bring in my plan')}<div class="help-card"><h3>Less planning. More doing.</h3><p>Tell ChatGPT what you’re studying and when you’re free. We’ll turn its JSON into your daily quests.</p><button class="primary" data-action="prompt">Get the ChatGPT prompt${icon('arrow')}</button></div>`;}
function habitsView(){
  const first=shift(today,-6),scheduled=state.habits.filter(h=>due(h,today)),done=scheduled.filter(h=>isDone('h',h,today)).length;
  return `<div class="page-heading"><div><p class="eyebrow">MAKE A LITTLE GOOD THING STICK</p><h1>Your daily<br>power-ups.</h1></div>${icon('heart')}</div><p class="subtitle">Small rituals. A stronger you. One check-in at a time.</p>
  <div class="habit-summary"><span class="habit-summary-icon">${icon('spark')}</span><div><strong data-habit-summary>${done} of ${scheduled.length} done today</strong><small>You don’t need perfect. You just need a start.</small></div><span class="habit-summary-score" data-habit-score>${done}/${scheduled.length}</span><div class="habit-progress-track"><span data-habit-progress style="width:${scheduled.length?done/scheduled.length*100:0}%"></span></div></div>
  <div class="section-head"><h2>Your habits<span>${state.habits.length}</span></h2><button class="text-button" data-action="add-habit">${icon('plus')}New habit</button></div>
  ${state.habits.map((h,i)=>{
    const done=isDone('h',h,today),active=due(h,today);
    const status=habitStatus(h);
    return `<article class="habit-full ${['green','pink','lilac','blue'][i%4]} ${done?'done':''}" data-habit-id="${escape(h.id)}">
    <div class="habit-full-top"><span class="habit-symbol">${icon(h.icon)}</span><div class="habit-text"><strong>${escape(h.title)}</strong><small>${escape(repeatLabel(h))}${h.endDate?' · until '+shortDate(h.endDate):''}</small></div><button class="icon-button" data-action="edit-habit" data-id="${escape(h.id)}" aria-label="Edit ${escape(h.title)}">${icon('edit')}</button></div>
    <button class="habit-mark ${done?'done':''}" data-action="complete" data-type="h" data-id="${escape(h.id)}" data-date="${today}" aria-label="${done?'Undo':'Complete'} ${escape(h.title)}" aria-pressed="${done}" ${active?'':'disabled'}><span class="habit-mark-icon">${icon(done?'check':'plus')}</span><span class="habit-mark-label">${done?'Done for today':active?'Mark as done':escape(status)}</span><span class="habit-mark-xp">${active?done?'✓':' +5 XP':icon('clock')}</span></button>
    <div class="habit-week-header"><span>YOUR LAST 7 DAYS</span><span data-habit-streak-label="${escape(h.id)}">${icon('flame')}<b data-habit-streak="${escape(h.id)}">${streak(h,state.completions,today)}</b> day streak</span></div>
    <div class="history-strip">${Array.from({length:7},(_,i)=>{const d=shift(first,i),scheduled=due(h,d),completed=isDone('h',h,d);return `<button class="history-day ${completed?'complete':''} ${!scheduled?'off':''} ${d===today?'current':''}" data-action="complete" data-type="h" data-id="${escape(h.id)}" data-date="${d}" aria-label="${completed?'Undo':'Mark done'} ${escape(h.title)} on ${longDate(d)}" aria-pressed="${completed}" ${!scheduled?'disabled':''}><span>${fromKey(d).toLocaleDateString(undefined,{weekday:'short'}).slice(0,1)}</span><span class="stamp">${icon('check')}<span class="day-number">${fromKey(d).getDate()}</span></span></button>`;}).join('')}</div>
    <p class="habit-card-note">${h.startDate>today?'Starts '+escape(shortDate(h.startDate)):h.endDate&&h.endDate<today?'Finished '+escape(shortDate(h.endDate)):'Tap a past day to add or undo a check-in.'}</p></article>`;
  }).join('')||empty('A tiny start is a big deal.','Choose a ritual you can show up for, even on a busy day.','add-habit','Create my first habit')}
  <div class="habit-starters"><p class="eyebrow">NEED A LITTLE INSPIRATION?</p><div>${['walk','chess','study'].map(key=>`<button data-action="habit-preset" data-preset="${key}">${icon(key==='study'?'book':key)}${{walk:'Morning walk',chess:'Play chess',study:'Study daily'}[key]}</button>`).join('')}</div></div><p class="local-note">Rest days don’t break your streak. A missed day? A fresh start is always here.</p>`;
}
function habitStatus(h){if(h.startDate>today)return 'Starts '+shortDate(h.startDate);if(h.endDate&&h.endDate<today)return 'Habit finished';return 'Rest day today';}

function moreView(){return `<div class="page-heading"><div><p class="eyebrow">YOUR LITTLE CORNER</p><h1>A brief<br>about you.</h1></div><span class="brand-mark">✳</span></div><div class="stats-grid"><div class="stat purple"><strong>${xp()}</strong><small>XP earned · Level ${Math.floor(xp()/100)+1}</small></div><div class="stat"><strong>${Object.keys(state.completions).length}</strong><small>Little wins, all time</small></div></div><div class="menu-card"><button class="menu-row" data-action="import">${icon('upload')}<span class="menu-copy"><strong>Import your plan</strong><small>Paste JSON or upload a file</small></span><span class="chevron">›</span></button><button class="menu-row" data-action="prompt">${icon('spark')}<span class="menu-copy"><strong>Let ChatGPT do the planning</strong><small>A ready-to-copy prompt, made for this app</small></span><span class="chevron">›</span></button><button class="menu-row" data-action="export">${icon('calendar')}<span class="menu-copy"><strong>Save a backup</strong><small>Your tasks, habits, and completed days</small></span><span class="chevron">↓</span></button></div><div class="menu-card"><button class="menu-row" data-action="sound" role="switch" aria-checked="${state.settings.sound}">${icon('volume')}<span class="menu-copy"><strong data-sound-label>${state.settings.sound?'Completion sound is on':'Completion sound is off'}</strong><small>A bright little chime with every win</small></span><span class="switch ${state.settings.sound?'on':''}"></span></button><button class="menu-row" data-action="motion" role="switch" aria-checked="${state.settings.motion}">${icon('heart')}<span class="menu-copy"><strong>Playful animations</strong><small>A bouncing buddy & celebration confetti</small></span><span class="switch ${state.settings.motion?'on':''}"></span></button></div><p class="local-note">Your tasks, habits, and progress stay on this device. Nothing is uploaded or synced to the cloud. Each phone or laptop has its own plan. Export a backup before clearing browser data or moving to another device.</p><p class="footer-note">MADE FOR SMALL STEPS & BIG DAYS ✳</p>`;}
function render(animate=false){today=dateKey();document.querySelectorAll('.bottom-nav button').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});app.innerHTML=`${!storageOK?'<div class="storage-warning" role="alert">Your browser storage could not be read or saved. Export a backup to keep any new changes.</div>':''}<div class="${animate?'view-enter':'view-content'}">${({today:todayView,plan:planView,habits:habitsView,more:moreView})[view]()}</div>`;syncSettings();}

function navigate(next){if(!['today','plan','habits','more'].includes(next))next='today';if(view===next&&app.children.length&&(next!=='today'||selected===today))return;view=next;if(next==='today')selected=today;history.replaceState(null,'',`#${next}`);render(true);window.scrollTo({top:0,behavior:'instant'});}

function openModal(title,content){dialog.setAttribute('aria-label',title);modalBody.innerHTML=`<div class="modal-content"><div class="modal-handle"></div><div class="modal-header"><h2>${escape(title)}</h2><button class="icon-button" data-action="close" aria-label="Close dialog">${icon('close')}</button></div>${content}</div>`;if(!dialog.open)dialog.showModal();}
function error(message){let box=document.querySelector('#form-error');if(!box){box=document.createElement('div');box.id='form-error';box.className='error';box.setAttribute('role','alert');modalBody.querySelector('.modal-content').append(box);}box.textContent=message;}
function taskForm(task){const t=task||{id:id(),title:'',date:selected,minutes:25,category:'study',notes:''};openModal(task?'Edit your quest':'A new little quest',`<form id="task-form" data-id="${escape(t.id)}"><label class="field">What are we doing?<input name="title" required maxlength="160" value="${escape(t.title)}" placeholder="e.g. Chapter 2: practice questions"></label><div class="field-row"><label class="field">Date<input name="date" type="date" required value="${t.date}"></label><label class="field">Time (optional)<input name="time" type="time" value="${t.time||''}"></label></div><div class="field-row"><label class="field">Minutes<input name="minutes" type="number" min="1" max="1440" required value="${t.minutes}"></label><label class="field">Kind of quest<select name="category">${['study','practice','review','personal'].map(c=>`<option value="${c}" ${c===t.category?'selected':''}>${{study:'Deep work',practice:'Practice',review:'Review',personal:'Personal'}[c]}</option>`).join('')}</select></label></div><label class="field">A note to future you<textarea name="notes" maxlength="4000" placeholder="What should you focus on?">${escape(t.notes)}</textarea></label><button class="primary" type="submit">${task?'Save changes':'Add to my day'}${icon('arrow')}</button>${task?'<button type="button" class="delete" data-action="delete-task" data-id="'+escape(t.id)+'">Delete this task</button>':''}</form>`);}
function habitForm(habit){const h=habit||{id:id(),title:'',startDate:today,repeat:'daily',icon:'heart'};openModal(habit?'Tweak your ritual':'Build a little ritual',`<form id="habit-form" data-id="${escape(h.id)}"><label class="field">Habit name<input name="title" required maxlength="160" value="${escape(h.title)}" placeholder="e.g. Morning walk"></label><div class="field-row"><label class="field">A little icon<select name="icon">${['heart','walk','chess','book','sun','spark'].map(i=>`<option value="${i}" ${i===h.icon?'selected':''}>${{heart:'♡ Heart',walk:'Walk',chess:'Chess',book:'Study',sun:'Sunshine',spark:'Sparkle'}[i]}</option>`).join('')}</select></label><label class="field">Repeat<select name="repeat" id="repeat-select"><option value="daily" ${h.repeat==='daily'?'selected':''}>Every day</option><option value="weekdays" ${h.repeat==='weekdays'?'selected':''}>Weekdays</option><option value="custom" ${Array.isArray(h.repeat)?'selected':''}>Choose days</option></select></label></div><div id="custom-days" class="custom-days" ${Array.isArray(h.repeat)?'':'hidden'}>${['mon','tue','wed','thu','fri','sat','sun'].map(d=>`<label><input type="checkbox" name="days" value="${d}" ${Array.isArray(h.repeat)&&h.repeat.includes(d)?'checked':''}>${d.slice(0,1).toUpperCase()+d.slice(1)}</label>`).join('')}</div><div class="field-row"><label class="field">Starts on<input type="date" name="startDate" required value="${h.startDate}"></label><label class="field">Ends on (optional)<input type="date" name="endDate" value="${h.endDate||''}"></label></div><p class="modal-description">One check-in per scheduled day. You can change your rhythm whenever life changes.</p><button class="primary" type="submit">${habit?'Save my ritual':'Let’s make it a habit'}${icon('heart')}</button>${habit?'<button type="button" class="delete" data-action="delete-habit" data-id="'+escape(h.id)+'">Delete this habit</button>':''}</form>`);}
function taskDetail(t){openModal('One step at a time',`<div class="task-icon ${t.category}" style="margin-bottom:17px">${icon('book')}</div><h3 style="font-size:21px;letter-spacing:-.6px;line-height:1.4;margin:0 0 10px">${escape(t.title)}</h3><p class="modal-description">${escape(longDate(t.date))}${t.time?' · '+escape(t.time):''} · ${t.minutes} minutes</p>${t.notes?`<div class="prompt" style="margin-bottom:20px">${escape(t.notes)}</div>`:''}<div class="form-actions"><button class="primary" data-action="start-task-focus" data-id="${escape(t.id)}">${icon('clock')}Focus on this</button><button class="secondary" data-action="edit-task" data-id="${escape(t.id)}">${icon('edit')}Edit</button></div>`);}
function samplePlan(){return {version:1,tasks:[{id:'study-chapter-1',title:'Study chapter 1',date:today,time:'09:00',minutes:45,category:'study',notes:'Read, then summarise the key ideas.'},{id:'practice-questions-1',title:'Solve 10 practice questions',date:shift(today,1),minutes:30,category:'practice'}],habits:[{id:'morning-walk',title:'Morning walk',repeat:'daily',startDate:today,icon:'walk'},{id:'chess',title:'Play a chess game',repeat:['mon','wed','fri'],startDate:today,icon:'chess'},{id:'studies',title:'Show up to study',repeat:'weekdays',startDate:today,icon:'book'}]};}
function importModal(){importDraft=null;openModal('A plan, brought to life',`<p class="modal-description">Paste the JSON ChatGPT made for you, or upload a .json file. We’ll check it before changing your plan.</p><div class="import-options"><button data-action="prompt">${icon('spark')}ChatGPT prompt</button><button data-action="sample">Try sample JSON</button><button data-action="upload-file">Upload .json</button></div><input id="json-file" type="file" accept=".json,application/json" hidden><label class="field">Your JSON<textarea id="json-input" class="code" spellcheck="false" placeholder='{ "version": 1, "tasks": [], "habits": [] }' aria-label="Paste your JSON plan"></textarea></label><button class="primary" data-action="preview-import">Check my plan${icon('arrow')}</button><div id="import-result"></div>`);}
function previewImport(){try{const text=document.querySelector('#json-input').value;if(text.length>5_000_000)throw Error('This file is too large. Use a JSON file smaller than 5 MB.');importDraft=normalizePlan(JSON.parse(text));document.querySelector('#form-error')?.remove();const ds=importDraft.tasks.map(t=>t.date).sort();document.querySelector('#import-result').innerHTML=`<div class="import-preview"><strong>Looks good! ${importDraft.tasks.length} tasks · ${importDraft.habits.length} habits</strong><p>${ds.length?`${shortDate(ds[0])} – ${shortDate(ds.at(-1))}. `:''}${importDraft.completions?Object.keys(importDraft.completions).length+' saved check-ins included.':'Ready to turn this into little wins.'}</p></div><label class="radio-row"><input type="radio" name="import-mode" value="merge" checked>Merge with my plan (matching IDs update)</label><label class="radio-row"><input type="radio" name="import-mode" value="replace">Replace plan & restore this file’s check-ins</label><button class="primary" data-action="confirm-import">Bring in my plan${icon('spark')}</button>`;}catch(e){importDraft=null;document.querySelector('#import-result').replaceChildren();error(e instanceof SyntaxError?'That isn’t valid JSON yet. Ask ChatGPT for JSON only, without Markdown code fences, or check the commas and quotation marks.':e.message);}}
function confirmImport(){if(!importDraft)return;const replace=document.querySelector('input[name="import-mode"]:checked')?.value==='replace';if(replace&&!confirm('Replace all existing tasks, habits, and check-ins with this file? Save a backup first if you want to keep them.'))return;const tasks=replace?importDraft.tasks:mergeEntries(state.tasks,importDraft.tasks),habits=replace?importDraft.habits:mergeEntries(state.habits,importDraft.habits);if(tasks.length>3000||habits.length>100){error('Your combined plan exceeds 3,000 tasks or 100 habits. Choose Replace or import a smaller plan.');return;}state.tasks=tasks;state.habits=habits;state.completions=replace?(importDraft.completions||{}):{...state.completions,...importDraft.completions};if(replace)state.focus=null;state.settings.starter=false;save();dialog.close();selected=today;navigate('today');celebrate();toast('Your new plan is here. Let’s make it happen!');importDraft=null;}
function promptText(){return `Create a study plan for My Daily Brief. Ask me about my subjects, available time, tasks, dates, and recurring habits if needed. Today is ${today} in my local timezone. Return valid JSON only, without Markdown fences or extra text.

Schema:
{"version":1,"tasks":[{"id":"unique-task-id","title":"Study chapter 1","date":"${today}","time":"09:00","minutes":45,"category":"study","notes":"What to do"}],"habits":[{"id":"unique-habit-id","title":"Morning walk","startDate":"${today}","repeat":"daily","icon":"walk"}]}

Rules: Give each task and habit a unique stable ID using letters, numbers, hyphens, or underscores. Dates are real YYYY-MM-DD dates. Tasks are one entry per date; minutes are whole numbers from 1 to 1440; time is optional 24-hour HH:MM; category is study, practice, review, or personal. Habit repeat is daily, weekdays, or an array of lowercase day codes such as ["mon","wed","fri"]. Habit endDate is optional; icon is walk, chess, book, heart, sun, or spark. Keep the schedule realistic and leave room for breaks. To update an existing item, reuse its ID. Include only the tasks and habits I ask for.

My subjects, dates, availability, and habits: [I will add these here]`;}
function promptModal(){openModal('Your ChatGPT shortcut',`<p class="modal-description">Copy this into ChatGPT. Add your subjects, dates, and habits at the end, then paste its JSON in Import.</p><div class="prompt" id="prompt-text">${escape(promptText())}</div><div class="form-actions"><button class="primary" data-action="copy-prompt">Copy prompt${icon('spark')}</button><button class="secondary" data-action="import">Import</button></div>`);}
async function copyPrompt(){const text=promptText();try{await navigator.clipboard.writeText(text);toast('Copied! Take it to ChatGPT.');}catch{const area=document.createElement('textarea');area.value=text;modalBody.append(area);area.select();const ok=document.execCommand('copy');area.remove();toast(ok?'Copied! Take it to ChatGPT.':'Press and hold the prompt above to copy it.');}}
function exportPlan(){const data={version:1,tasks:state.tasks,habits:state.habits,completions:state.completions};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`my-daily-brief-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Backup ready. Keep it somewhere safe.');}
function remaining(){if(!state.focus)return 0;return state.focus.endAt?Math.max(0,Math.ceil((state.focus.endAt-Date.now())/1000)):state.focus.remaining;}
function timerText(){const n=remaining();return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function focusModal(taskId){if(taskId){if(state.focus&&state.focus.taskId!==taskId&&!confirm('End the current focus session and start with this task?'))return;if(!state.focus||state.focus.taskId!==taskId){const t=state.tasks.find(t=>t.id===taskId);timerPreset=t.minutes;state.focus={taskId,remaining:timerPreset*60,endAt:null};save();}}const t=state.tasks.find(t=>t.id===state.focus?.taskId);openModal('A little focus time',`<div class="timer-screen"><div class="timer-art">${icon('book')}</div><h3 style="font-size:17px;margin:0">${escape(t?.title||'Make some room for deep work')}</h3><div class="timer-count" data-timer-label>${state.focus?timerText():'25:00'}</div><p id="timer-status">${state.focus?.endAt?'One thing at a time. You’re doing great.':'Put your phone down. Let your brain do its thing.'}</p>${!state.focus?.endAt?`<div class="timer-presets">${[15,25,45].map(n=>`<button data-action="timer-preset" data-minutes="${n}" class="${n===timerPreset?'active':''}">${n} min</button>`).join('')}</div>`:''}<button class="primary" data-action="timer-toggle">${state.focus?.endAt?'Pause focus':'Start focus'}${icon('clock')}</button>${state.focus?'<button class="delete" data-action="timer-stop">End this session</button>':''}</div>`);}
function timerToggle(){if(!state.focus)state.focus={taskId:null,remaining:timerPreset*60,endAt:null};if(state.focus.endAt){state.focus.remaining=remaining();state.focus.endAt=null;}else state.focus.endAt=Date.now()+Math.max(state.focus.remaining,1)*1000;save();focusModal();syncFocusBanner();}
function syncProgress(){
  const tasks=[...app.querySelectorAll('[data-task-id]')].map(el=>state.tasks.find(t=>t.id===el.dataset.taskId)).filter(Boolean);
  const habits=state.habits.filter(h=>due(h,selected)),doneTasks=tasks.filter(t=>isDone('t',t,t.date)).length,doneHabits=habits.filter(h=>isDone('h',h,selected)).length;
  const done=doneTasks+doneHabits,total=tasks.length+habits.length,percent=total?Math.round(done/total*100):0;
  const ring=app.querySelector('.progress-ring');if(ring){ring.style.setProperty('--progress',percent+'%');ring.dataset.percent=percent+'%';ring.setAttribute('aria-label',percent+' percent complete');}
  const title=app.querySelector('.progress-text strong'),count=app.querySelector('.progress-text span');if(title)title.textContent=done===total&&total?'A beautifully finished day':done?'Little wins are adding up':'Let’s get your first little win';if(count)count.textContent=`${done} of ${total} things completed`;
  const dayXP=app.querySelector('.xp-label');if(dayXP)dayXP.lastChild.textContent=`+${doneTasks*10+doneHabits*5} XP`;
  const pill=app.querySelector('.streak-pill');if(pill)pill.lastChild.textContent=`${dailyStreak()} day${dailyStreak()===1?'':'s'}`;
  const hero=app.querySelector('.hero-copy');if(hero){const allDone=total>0&&done===total;hero.querySelector('.eyebrow').textContent=allDone?'LOOK AT YOU GO':'A FRESH LITTLE START';hero.querySelector('h2').innerHTML=allDone?'You showed up.<br>That’s a win.':'Small steps.<br>Big possibilities.';hero.querySelector('p').innerHTML=allDone?'Take a breath. You earned it.':'A little focus, a little fun.<br>You’ve got this.';}
  const scheduled=state.habits.filter(h=>due(h,today)),completed=scheduled.filter(h=>isDone('h',h,today)).length;
  const summary=app.querySelector('[data-habit-summary]');if(summary)summary.textContent=`${completed} of ${scheduled.length} done today`;
  const score=app.querySelector('[data-habit-score]');if(score)score.textContent=`${completed}/${scheduled.length}`;
  const progress=app.querySelector('[data-habit-progress]');if(progress)progress.style.width=(scheduled.length?completed/scheduled.length*100:0)+'%';
}
function syncCompletion(type,item,date){
  const done=isDone(type,item,date);
  app.querySelectorAll('[data-action="complete"]').forEach(button=>{
    if(button.dataset.type!==type||button.dataset.id!==item.id||button.dataset.date!==date)return;
    button.classList.toggle('done',done);button.setAttribute('aria-pressed',String(done));
    button.setAttribute('aria-label',`${done?'Undo':'Complete'} ${item.title}${button.classList.contains('history-day')?' on '+longDate(date):''}`);
    if(button.classList.contains('history-day'))button.classList.toggle('complete',done);
    button.closest('.task, .habit-card')?.classList.toggle('done',done);
    const mark=button.querySelector('.habit-mark-label');if(mark)mark.textContent=done?'Done for today':'Mark as done';
    const xp=button.querySelector('.habit-mark-xp');if(xp)xp.textContent=done?'✓':'+5 XP';
    const symbol=button.querySelector('.habit-mark-icon use');if(symbol)symbol.setAttribute('href',done?'#i-check':'#i-plus');
    button.closest('.task')?.querySelector('.overdue')?.toggleAttribute('hidden',done);
  });
  if(type==='h'){
    app.querySelectorAll('[data-habit-streak]').forEach(el=>{if(el.dataset.habitStreak===item.id)el.textContent=streak(item,state.completions,today);});
    app.querySelectorAll('.habit-full[data-habit-id]').forEach(card=>{if(card.dataset.habitId===item.id)card.classList.toggle('done',isDone('h',item,today));});
  }
  syncProgress();
}
function complete(type,itemId,date,origin){
  const changed=toggleCompletion(state,type,itemId,date,today);if(!changed)return;
  const {item,done}=changed;
  if(done&&type==='t'&&state.focus?.taskId===itemId){state.focus=null;app.querySelector('.active-focus')?.remove();}
  save();syncCompletion(type,item,date);
  if(done){origin?.classList.add('just-completed');setTimeout(()=>origin?.classList.remove('just-completed'),450);celebrate(origin,type==='t'?10:5);toast(type==='t'?'Quest complete! +10 XP':'Habit complete! +5 XP');}
  else{void playFeedback('tap');toast('Undone. You can check it off again anytime.');}
  if(type==='t'){
    const list=origin?.closest('.task')?.parentElement;
    if(list){const ids=[...list.children].filter(el=>el.dataset.taskId).map(el=>el.dataset.taskId);const tasks=state.tasks.filter(t=>ids.includes(t.id));reorderTaskCards(list,orderTasks(tasks,state.completions).map(t=>t.id),state.settings.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches);}
  }
}

document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
  if(a==='navigate'){e.preventDefault();navigate(b.dataset.view);}
  else if(a==='date'){selected=b.dataset.date;render();}
  else if(a==='close')dialog.close();
  else if(a==='complete')complete(b.dataset.type,b.dataset.id,b.dataset.date,b);
  else if(a==='add-task')taskForm();
  else if(a==='add-habit')habitForm();
  else if(a==='habit-preset'){habitForm();const preset={walk:['Morning walk','walk'],chess:['Play chess','chess'],study:['Study daily','book']}[b.dataset.preset];document.querySelector('#habit-form input[name="title"]').value=preset[0];document.querySelector('#habit-form select[name="icon"]').value=preset[1];}
  else if(a==='edit-task')taskForm(state.tasks.find(t=>t.id===b.dataset.id));
  else if(a==='edit-habit')habitForm(state.habits.find(h=>h.id===b.dataset.id));
  else if(a==='task-detail')taskDetail(state.tasks.find(t=>t.id===b.dataset.id));
  else if(a==='delete-task'||a==='delete-habit'){const type=a==='delete-task'?'tasks':'habits';if(confirm('Delete this '+(type==='tasks'?'task':'habit')+'? Your earned XP and past check-ins will be kept.')){state[type]=state[type].filter(t=>t.id!==b.dataset.id);if(state.focus?.taskId===b.dataset.id)state.focus=null;state.settings.starter=false;save();dialog.close();render();toast('Removed from your plan.');}}
  else if(a==='import')importModal();
  else if(a==='prompt')promptModal();
  else if(a==='copy-prompt')await copyPrompt();
  else if(a==='sample'){document.querySelector('#json-input').value=JSON.stringify(samplePlan(),null,2);document.querySelector('#json-input').dispatchEvent(new Event('input',{bubbles:true}));}
  else if(a==='upload-file')document.querySelector('#json-file').click();
  else if(a==='preview-import')previewImport();
  else if(a==='confirm-import')confirmImport();
  else if(a==='export')exportPlan();
  else if(a==='sound')await toggleSound();

  else if(a==='motion'){state.settings.motion=!state.settings.motion;applyMotion();save();syncSettings();toast(state.settings.motion?'Playful animations on':'Animations off');}

  else if(a==='start-task-focus')focusModal(b.dataset.id);
  else if(a==='focus')focusModal();
  else if(a==='timer-toggle')timerToggle();
  else if(a==='timer-preset'){timerPreset=Number(b.dataset.minutes);if(state.focus){state.focus.remaining=timerPreset*60;state.focus.endAt=null;save();}focusModal();}
  else if(a==='timer-stop'){state.focus=null;save();dialog.close();app.querySelector('.active-focus')?.remove();toast('Focus session ended. Every minute counts.');}
});
document.addEventListener('submit',e=>{if(!['task-form','habit-form'].includes(e.target.id))return;e.preventDefault();const f=e.target,data=new FormData(f);try{
  if(f.id==='task-form'){const t={id:f.dataset.id,title:data.get('title'),date:data.get('date'),minutes:Number(data.get('minutes')),category:data.get('category'),notes:data.get('notes'),...(data.get('time')?{time:data.get('time')}:{})},clean=normalizePlan({tasks:[t]}).tasks[0];if(!state.tasks.some(x=>x.id===clean.id)&&state.tasks.length>=3000)throw Error('Your plan already has 3,000 tasks. Remove some before adding another.');state.tasks=mergeEntries(state.tasks,[clean]);selected=clean.date;}
  else{const h={id:f.dataset.id,title:data.get('title'),startDate:data.get('startDate'),repeat:data.get('repeat')==='custom'?data.getAll('days'):data.get('repeat'),icon:data.get('icon'),...(data.get('endDate')?{endDate:data.get('endDate')}:{})},clean=normalizePlan({habits:[h]}).habits[0];if(!state.habits.some(x=>x.id===clean.id)&&state.habits.length>=100)throw Error('You already have 100 habits. Remove one before adding another.');state.habits=mergeEntries(state.habits,[clean]);}
  state.settings.starter=false;save();dialog.close();render();toast(f.id==='task-form'?'Your quest is ready.':'A little ritual, a fresh start.');
}catch(err){error(err.message);}});
document.addEventListener('change',async e=>{if(e.target.matches('[data-date-picker]')&&e.target.value){selected=e.target.value;render();}if(e.target.id==='repeat-select')document.querySelector('#custom-days').hidden=e.target.value!=='custom';if(e.target.id==='json-file'){const file=e.target.files[0];if(!file)return;if(file.size>5_000_000){error('Use a JSON file smaller than 5 MB.');return;}try{const text=await file.text();const input=document.querySelector('#json-input');if(input){input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));previewImport();}}catch{error('That file could not be read. Try pasting the JSON instead.');}}});
document.addEventListener('input',e=>{if(e.target.id==='json-input'){importDraft=null;document.querySelector('#import-result')?.replaceChildren();document.querySelector('#form-error')?.remove();}});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)dialog.close();}});
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
setInterval(()=>{if(today!==dateKey()){const wasToday=selected===today;today=dateKey();if(wasToday)selected=today;render();}if(state.focus){document.querySelectorAll('[data-timer-label]').forEach(el=>el.textContent=timerText());if(state.focus.endAt&&remaining()<=0){state.focus=null;save();app.querySelector('.active-focus')?.remove();if(dialog.open&&document.querySelector('.timer-screen'))openModal('Look at you, focused.',`<div class="timer-screen"><div class="timer-art">${icon('spark')}</div><h3>That’s time well spent.</h3><p>Your focus session is complete. Mark your task done when you’re ready.</p><button class="primary" data-action="close">Back to my day${icon('check')}</button></div>`);celebrate();toast('Focus finished! Take a well-earned break.');}}},1000);
navigate(location.hash.slice(1)||'today');

// No install UI: keep the browser's native installation behavior. Only app files are cached.
if(globalThis.navigator?.serviceWorker){
  window.addEventListener('load',()=>{
    navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{});
  });
}
